### ISSUE TITLE
QuickPay-Callback-Url

### ISSUE THREAD

**Issue by YnkDK** [QuickPay/quickpay-python-client#10]
It is not possible to change the header QuickPay-Callback-Url using this client.

This would be useful when it is not accepted in the body, e.g. 
[POST /subscriptions/{id}/recurring](https://learn.quickpay.net/tech-talk/api/services/#POST-subscriptions--id-recurring---format-)

**Comment by mstendorf** [comment]
I made a homegrown attempt at fixing this in my fork.

I did not make a pull request cause the fix is rather dirty, but it does the trick for anyone in dire need of a solution.
https://github.com/mstendorf/quickpay-python-client

**Comment by YnkDK** [comment]
It looks a bit like the solution I ended up with. However I made a `pop` on `kwargs` with a default value of `None`. Other than that we ended up with the same result :)

**Comment by lyprono** [comment]
Hello DO you have fix the problem? i have got that problem too  while i have called back to my url  that i don't get any response
