### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by grzennio** [QuickPay/quickpay-python-client#15]
Hi, for start, we use QuickPay for transactions.
Few days ago our client, complaint that he can't make payments.
This is snippet from the error: 

> Request Method: | POST-- | --  1.8.3 SSLError
>  EOF occurred in violation of protocol (_ssl.c:581)
>  ********/local/lib/python2.7/site-packages/requests/adapters.py in send, line 431
> /usr/bin/uwsgi-core
>  Python Versin: 2.7.9

requirements.txt contains:

> Django==1.11
> requests==2.13.0
> git+https://github.com/QuickPay/quickpay-python-client.git

Thanks for any reply.

**Comment by ta** [comment]
@accuku Support for TLSv1.0 has been terminated since the end of june. Our python client has been updated and a [new release](https://pypi.org/project/quickpay-api-client/#history) (1.0.1) created.

If you update the client it should work again.

**Comment by grzennio** [comment]
Okey ill try it.

**Comment by ta** [comment]
@accuku Hmm... that could be. I'm gonna transfer you to our resident python expert, who will get back to you asap.

**Comment by dinesh** [comment]
@accuku Could you update the `quickpay-api-client`  to `1.0.1`, Hopefully, it should work, otherwise let me know.

**Comment by grzennio** [comment]
Okey so it was just problem with package, i wasn't the one who write this project and i didn't realize that you've change name of package in some commit, which causes problems.
Thanks for your help and time.
It can be closed.
