### ISSUE TITLE
Update version and push to PyPi

### ISSUE THREAD

**Issue by colde** [QuickPay/quickpay-python-client#9]
With the new status_code added to the ApiError exception. Could somebody update the version and push to PyPi please? I am happy to update the version in a pull request, but it seems a bit unnecessary.

**Comment by ta** [comment]
Looking at it now :)

**Comment by ta** [comment]
Done - https://pypi.python.org/pypi?:action=display&name=quickpay-api-client&version=1.0.0 :)
